### PR TITLE
col_generation: add Diff stage wrapping pandas.diff (#9)

### LINKED ISSUE #9: Diff transformer
Hi,

Pdpipe is marvelous, very nice tool!

One addon possibility that I was wondering:
In case of time series, de-trending is a common operation, done by taking the first differential of the data eg. with `pd.DataFrame.diff(1)`. The problem with this is, that the initial value gets dropped and there is no easy way to "back transform".
Here a "fittable", Scikit like transformer could come in handy. 

I have sketched such a thing for myself here: https://gist.github.com/solalatus/9a3fc5330e7c0cd83e61094db75d2dc3

Can this be interesting as an addition?
Many thanks!

### PR DESCRIPTION
**Pull request by jbbqqf**
Resolves #9

## Summary

Add a `pdp.Diff` column-generation stage that wraps `pandas.Series.diff(periods)` per column, so first-differences (the standard de-trending primitive for time-series-shaped data) can compose with the rest of a pdpipe pipeline.

## Context

Issue #9 (open since 2019-10-13, labelled `good first issue` + `help wanted`) asks for a "Scikit-like transformer" for first differences. The maintainer green-lit this in 2019-12-03 ("Yes, definitely!"), with the caveat that pdpipe stages don't yet expose `inverse_transform`, so the invertibility ask is deferred to the broader effort tracked in #64. This PR ships the forward-only stage requested in the issue body; it does not touch invertibility.

## Changes

- `src/pdpipe/col_generation.py`: new `Diff` class (subclasses `ColumnsBasedPipelineStage`, same shape as `Log` / `AggByCols`). Defaults to all numeric columns when `columns=None`, supports `periods` (validated as int at construction), `drop` (replace source vs. add suffix), and a customisable `suffix`. Stateless across fit/transform, so the two paths share one implementation. Inline comments explain the non-obvious choices (the constructor validation, the stateless rationale, the deferred inverse-transform).
- `src/pdpipe/__init__.py`: re-export `Diff` and add it to `__all__`.
- `tests/col_generation/test_diff.py`: 10 unit tests covering defaults, `drop=True`, `periods=2`, `periods=-1`, numeric-only auto-selection, custom suffix, invalid-periods rejection, transform-after-fit, in-pipeline composition, and pickle round-trip.
- `tests/test_issue_9.py`: 3 sentinel tests pinned to issue #9 (matches the `tests/test_issue_70.py` convention introduced in PR #147). Fails on `origin/master`, passes here.

## Reproduce BEFORE/AFTER yourself (copy-paste)

```bash
# --- one-time setup ---
git clone https://github.com/pdpipe/pdpipe.git /tmp/repro && cd /tmp/repro
python3 -m venv .venv && source .venv/bin/activate
pip install -e . -r tests/requirements.txt -q

git fetch https://github.com/jbbqqf/pdpipe.git feat/9-diff-transformer:pr9

# --- BEFORE (origin/master) ---
git checkout origin/master
python -c "import pdpipe as pdp; print(hasattr(pdp, 'Diff'))"
# Expected: False  — pdp.Diff does not exist yet

# --- AFTER (this PR) ---
git checkout pr9
# import the regression test from the PR branch (BEFORE has no copy of it)
python -c "import pdpipe as pdp; import pandas as pd
df = pd.DataFrame({'t': [1,2,3,4], 'val': [100,110,95,130]})
print(pdp.Diff('val')(df))"
# Expected: a DataFrame with columns t, val, val_diff where
#          val_diff = [NaN, 10.0, -15.0, 35.0]

pytest tests/test_issue_9.py tests/col_generation/test_diff.py -v --no-cov
# Expected: 13 passed
```

## What I ran locally

- `pytest tests/col_generation/test_diff.py tests/test_issue_9.py --no-cov` → 13/13 passed.
- `pytest src/pdpipe/col_generation.py::pdpipe.col_generation.Diff --doctest-modules --no-cov` → 1/1 passed (Diff doctest).
- `pytest tests/col_generation/ --no-cov` → 77 passed, 2 pre-existing failures in `test_onehotencode.py` related to `Pandas4Warning` for `select_dtypes('object')` — present on `origin/master` too, unrelated to this change.
- `pytest tests/ --no-cov` → 13 failures on this branch vs 15 on `origin/master`; all 13 are the same `Pandas4Warning` issue in unrelated stages (`encode`, `col_dtype_enforcer`, `skintegrate`, `onehotencode`). This PR adds 13 new passing tests and 0 new failures.
- `ruff check` on the new code: `Diff` itself adds 0 new ruff errors; the test files' 2 warnings (one S301 on `pickle.load`, one I001 import-ordering) match the same warnings already accepted in `tests/col_generation/test_log.py:309`.
- `black --check` on all 4 changed files → all pass.

## Edge cases tested

| # | Scenario | Input | Expected | Verified by |
|---|----------|-------|----------|-------------|
| 1 | Default `periods=1`, `drop=False` | numeric col `[100,110,95,130]` | `[NaN, 10, -15, 35]` appended as `<col>_diff` | `test_diff_default` |
| 2 | `drop=True` | same | source column replaced in place; first row `NaN` | `test_diff_drop_replaces_source` |
| 3 | `periods=2` | same | first two rows `NaN`, then `[..., -5, 20]` | `test_diff_periods_two` |
| 4 | `periods=-1` (forward diff) | same | last row becomes `NaN`, rest negated | `test_diff_periods_negative` |
| 5 | `columns=None` on mixed-dtype frame | int + float + str | only int and float get `_diff` columns; str untouched | `test_diff_default_columns_picks_numeric` |
| 6 | `periods=1.5` (or `"1"`) | invalid | `TypeError` raised at construction (not on first apply) | `test_diff_invalid_periods_raises` |
| 7 | Pickle round-trip | fitted stage | unpickled stage produces same output | `test_diff_pickle` |
| 8 | Compose in `pdp.PdPipeline` | `Diff('val')` then `ColDrop('val')` | only `val_diff` survives | `test_diff_in_pipeline` |

## Risk / blast radius

- Purely additive: a new stage, two import-line additions in `__init__.py`. No existing stage's behaviour is changed.
- The `OfDtypes([np.number])` default selector matches `Log`'s convention exactly, so users who already know `Log` won't be surprised.
- No new dependencies — `pandas.Series.diff` ships with the existing pandas requirement.
- `Diff` is stateless, so it does not introduce new pickling pitfalls beyond what every other stateless stage already does (covered by `test_diff_pickle`).

## Release note

```release-note
Add `pdp.Diff` column-generation stage that wraps `pandas.Series.diff(periods)` per column, useful for time-series detrending. Supports `drop=True` to replace columns in place, custom `suffix`, and negative `periods`. No `inverse_transform` (tracked in #64).
```

---

*PR drafted with assistance from Claude Code, working from a copy of `pdpipe/pdpipe@3140064` cloned into a worktree on a personal fork. The change was reviewed manually against the cited issue thread (#9) and the `Log` / `AggByCols` reference implementations in `col_generation.py`. The reproducer block above was used during development; it is the same one a reviewer can paste verbatim.*

### CODE REVIEW

**Comment by jbbqqf** [comment]
**Note on `pre-commit.ci - pr` check status**

The `pre-commit.ci - pr` check ERRORs on every PR in this repo right now (including the recently merged #160) because `docformatter v1.7.7` (pinned in `.pre-commit-config.yaml`) transitively depends on `untokenize`, whose sdist fails to build on Python 3.12+ with `AttributeError: 'Constant' object has no attribute 's'`. The hook environment never installs.

Commit [`174d585`](https://github.com/pdpipe/pdpipe/pull/161/commits/174d585) bumps `docformatter` to v1.7.8 (which dropped the `untokenize` dep), so pre-commit.ci's environment now installs cleanly. With that fixed, pre-commit.ci then surfaces some pre-existing master drift (1 line in `src/pdpipe/exceptions.py`, plus a docstring reflow in `skintegrate.py` and one ruff-format change). The repo's own `autofix_prs: true` policy means the bot pushed those fixes back automatically — they are visible in this PR but are unrelated to issue #9. Happy to remove them or split them into a separate housekeeping PR if you'd prefer the diff stay focused.

> AI disclosure: this comment was drafted by an AI agent (Claude Opus 4.7) acting on behalf of @jbbqqf.
